### ISSUE TITLE
Link and Link Text not getting read from initial config

### ISSUE THREAD

**Issue by perilandmishap** [charity-dynamics/charitydynamics-build-tool#3]
When loading a message view for the first time the Link and Link Text are not displayed.

Note that emails should not have either of these fields, and that only facebook messages use Link Text.

**Comment by eriksecker** [comment]
I've added logic so that the Link Text only displays when the channel is Facebook and so that the Link does not display if the channel is Email.
In terms of the link not displaying, I think given the logic that is in place, this is working as expected, though perhaps the logic needs to be reworked.  Basically, the system builds the dropdown list of available links from the list of links in programConfig.  When the value specified in the message gets bound to this dropdown but a matching link from program config is not found, the bound value is getting reset to the default "--choose--" selection with a value of "".
In terms of the Link Text not displaying, I believe it is.  Most of the values being sent down from the API are just "".

**Comment by perilandmishap** [comment]
Fixed bug that caused link id's in messages to not line up with the link id's in the program config.  Yes mostly the value of the Action Label in our test data is "", this defaults to "Donate" in the app.

Closing ticket - links look like they're working well.
